const fs = require('fs');
const path = require('path');

const blogDir = path.join(__dirname, '../src/content/blog');
const demosDir = path.join(__dirname, '../public/demos');

// Define beautiful premium templates for each category
const templates = {
  'HTML & CSS': {
    html: '<div class="premium-layout">\n  <header class="header"><h1>${title}</h1></header>\n  <main class="grid-content">\n    <section class="card"><h3>Flexbox Area</h3><p>Smooth glassmorphism and modern shadows.</p></section>\n    <section class="card"><h3>CSS Grid Area</h3><p>Responsive layout structure.</p></section>\n  </main>\n</div>',
    css: '.premium-layout { min-height: 100vh; background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); padding: 2rem; font-family: "Segoe UI", sans-serif; }\n.header h1 { text-align: center; color: #2c3e50; font-weight: 800; font-size: 2.5rem; text-shadow: 2px 2px 4px rgba(0,0,0,0.1); margin-bottom: 2rem; }\n.grid-content { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 2rem; max-width: 1000px; margin: 0 auto; }\n.card { background: rgba(255, 255, 255, 0.7); backdrop-filter: blur(10px); border-radius: 20px; padding: 2rem; box-shadow: 0 15px 35px rgba(0,0,0,0.1); border: 1px solid rgba(255,255,255,0.5); transition: transform 0.3s, box-shadow 0.3s; }\n.card:hover { transform: translateY(-10px); box-shadow: 0 25px 45px rgba(0,0,0,0.15); }\n.card h3 { color: #34495e; margin-bottom: 1rem; }',
    js: 'console.log("HTML & CSS layout initialized.");'
  },
  'Navigation Bar': {
    html: '<nav class="glass-nav">\n  <div class="logo">${title}</div>\n  <ul class="nav-links">\n    <li><a href="#">Home</a></li>\n    <li><a href="#">Features</a></li>\n    <li><a href="#">Pricing</a></li>\n    <li><a href="#" class="cta-btn">Get Started</a></li>\n  </ul>\n</nav>\n<div class="hero">Scroll down to see the navbar effect!</div>',
    css: 'body { margin: 0; font-family: "Inter", sans-serif; height: 200vh; background: #0f172a; color: #fff; }\n.glass-nav { position: fixed; top: 0; width: 100%; display: flex; justify-content: space-between; align-items: center; padding: 1.5rem 5%; background: rgba(15, 23, 42, 0.8); backdrop-filter: blur(12px); border-bottom: 1px solid rgba(255,255,255,0.1); z-index: 1000; transition: padding 0.3s; box-sizing: border-box; }\n.glass-nav.scrolled { padding: 1rem 5%; background: rgba(15, 23, 42, 0.95); box-shadow: 0 4px 30px rgba(0,0,0,0.5); }\n.logo { font-size: 1.5rem; font-weight: 800; background: linear-gradient(45deg, #00f2fe, #4facfe); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }\n.nav-links { list-style: none; display: flex; gap: 2rem; margin: 0; padding: 0; align-items: center; }\n.nav-links a { color: #cbd5e1; text-decoration: none; font-weight: 500; transition: color 0.3s; }\n.nav-links a:hover { color: #fff; }\n.cta-btn { background: #3b82f6; padding: 0.75rem 1.5rem; border-radius: 30px; color: #fff !important; font-weight: 600; box-shadow: 0 4px 15px rgba(59, 130, 246, 0.4); transition: transform 0.2s; }\n.cta-btn:hover { transform: translateY(-2px); background: #2563eb; }\n.hero { display: flex; justify-content: center; align-items: center; height: 100vh; font-size: 2rem; font-weight: 700; opacity: 0.5; }',
    js: "window.addEventListener('scroll', () => {\n  const nav = document.querySelector('.glass-nav');\n  if (window.scrollY > 50) { nav.classList.add('scrolled'); }\n  else { nav.classList.remove('scrolled'); }\n});"
  },
  'JavaScript Projects': {
    html: '<div class="app-container">\n  <h2>${title}</h2>\n  <div class="input-group">\n    <input type="text" id="item-input" placeholder="Enter an item...">\n    <button id="add-btn">Add</button>\n  </div>\n  <ul id="item-list" class="item-list"></ul>\n</div>',
    css: 'body { background: #1e1e2f; display: flex; justify-content: center; align-items: center; min-height: 100vh; font-family: "Segoe UI", sans-serif; margin: 0; }\n.app-container { background: #2a2a40; padding: 2.5rem; border-radius: 20px; box-shadow: 0 20px 50px rgba(0,0,0,0.3); width: 100%; max-width: 450px; color: #fff; border: 1px solid rgba(255,255,255,0.05); }\nh2 { text-align: center; margin-top: 0; color: #00e5ff; margin-bottom: 2rem; }\n.input-group { display: flex; gap: 10px; margin-bottom: 2rem; }\ninput { flex: 1; padding: 12px 20px; border-radius: 30px; border: none; background: #1e1e2f; color: #fff; font-size: 1rem; outline: none; box-shadow: inset 0 2px 5px rgba(0,0,0,0.2); }\nbutton { padding: 12px 25px; border-radius: 30px; border: none; background: #00e5ff; color: #1e1e2f; font-weight: bold; cursor: pointer; transition: 0.3s; font-size: 1rem; }\nbutton:hover { background: #00b3cc; transform: scale(1.05); }\n.item-list { list-style: none; padding: 0; margin: 0; }\n.item-list li { background: #383854; padding: 15px 20px; border-radius: 12px; margin-bottom: 10px; display: flex; justify-content: space-between; align-items: center; animation: fadeIn 0.3s ease; }\n.delete-btn { background: #ff4757; color: #fff; padding: 5px 12px; border-radius: 8px; font-size: 0.8rem; border: none; cursor: pointer; }\n.delete-btn:hover { background: #ff6b81; }\n@keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }',
    js: "const input = document.getElementById('item-input');\nconst addBtn = document.getElementById('add-btn');\nconst list = document.getElementById('item-list');\n\naddBtn.addEventListener('click', addItem);\ninput.addEventListener('keypress', (e) => { if(e.key === 'Enter') addItem(); });\n\nfunction addItem() {\n  if(!input.value.trim()) return;\n  const li = document.createElement('li');\n  li.innerHTML = '<span>' + input.value + '</span> <button class=\"delete-btn\">X</button>';\n  li.querySelector('.delete-btn').addEventListener('click', () => li.remove());\n  list.appendChild(li);\n  input.value = '';\n}"
  },
  'Form Validation': {
    html: '<div class="form-wrapper">\n  <h2>${title}</h2>\n  <form id="val-form">\n    <div class="form-control">\n      <label>Email Address</label>\n      <input type="email" id="email" placeholder="john@example.com">\n      <small>Error message</small>\n    </div>\n    <div class="form-control">\n      <label>Password</label>\n      <input type="password" id="password" placeholder="Min 8 characters">\n      <small>Error message</small>\n    </div>\n    <button type="submit" class="submit-btn">Register</button>\n  </form>\n</div>',
    css: 'body { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); font-family: "Inter", sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }\n.form-wrapper { background: #fff; padding: 40px; border-radius: 15px; box-shadow: 0 15px 30px rgba(0,0,0,0.2); width: 100%; max-width: 400px; box-sizing: border-box; }\nh2 { text-align: center; color: #333; margin-bottom: 30px; }\n.form-control { margin-bottom: 20px; position: relative; }\n.form-control label { display: block; margin-bottom: 8px; color: #666; font-weight: 500; font-size: 0.9rem; }\n.form-control input { width: 100%; padding: 12px; border: 2px solid #e2e8f0; border-radius: 8px; font-size: 1rem; box-sizing: border-box; transition: border-color 0.3s; }\n.form-control input:focus { outline: none; border-color: #667eea; }\n.form-control.error input { border-color: #e74c3c; }\n.form-control.success input { border-color: #2ecc71; }\n.form-control small { color: #e74c3c; position: absolute; bottom: -20px; left: 0; visibility: hidden; font-size: 0.8rem; }\n.form-control.error small { visibility: visible; }\n.submit-btn { width: 100%; padding: 14px; border: none; border-radius: 8px; background: #667eea; color: #fff; font-size: 1.1rem; font-weight: 600; cursor: pointer; transition: background 0.3s; margin-top: 10px; }\n.submit-btn:hover { background: #5a67d8; }',
    js: "const form = document.getElementById('val-form');\nconst email = document.getElementById('email');\nconst password = document.getElementById('password');\n\nform.addEventListener('submit', e => {\n  e.preventDefault();\n  checkInputs();\n});\n\nfunction checkInputs() {\n  const emailValue = email.value.trim();\n  const passwordValue = password.value.trim();\n  \n  if(emailValue === '') { setError(email, 'Email cannot be blank'); }\n  else if (!/^\\\\S+@\\\\S+\\\\.\\\\S+$/.test(emailValue)) { setError(email, 'Not a valid email'); }\n  else { setSuccess(email); }\n  \n  if(passwordValue === '') { setError(password, 'Password cannot be blank'); }\n  else if(passwordValue.length < 8) { setError(password, 'Min 8 characters required'); }\n  else { setSuccess(password); }\n}\n\nfunction setError(input, message) {\n  const formControl = input.parentElement;\n  formControl.className = 'form-control error';\n  formControl.querySelector('small').innerText = message;\n}\n\nfunction setSuccess(input) {\n  const formControl = input.parentElement;\n  formControl.className = 'form-control success';\n}"
  },
  'Preloader or Loader': {
    html: '<div class="loader-bg">\n  <div class="loader-container">\n    <div class="spinner"></div>\n    <h3>${title}</h3>\n  </div>\n</div>',
    css: 'body { margin: 0; background: #111; display: flex; justify-content: center; align-items: center; height: 100vh; font-family: "Inter", sans-serif; color: #fff; }\n.loader-container { display: flex; flex-direction: column; align-items: center; gap: 2rem; }\n.spinner { width: 80px; height: 80px; border-radius: 50%; border: 8px solid rgba(255,255,255,0.1); border-top-color: #00ff88; animation: spin 1s linear infinite; box-shadow: 0 0 20px rgba(0, 255, 136, 0.4); }\n@keyframes spin { 100% { transform: rotate(360deg); } }\nh3 { margin: 0; font-weight: 400; letter-spacing: 2px; text-transform: uppercase; color: #00ff88; text-shadow: 0 0 10px rgba(0, 255, 136, 0.5); }',
    js: "console.log('Loader animation running natively via CSS.');"
  },
  'Card Design': {
    html: '<div class="card-container">\n  <div class="modern-card">\n    <div class="card-img"></div>\n    <div class="card-info">\n      <h3>${title}</h3>\n      <p>A beautiful premium card design featuring hover transitions, modern typography, and clean layouts.</p>\n      <button class="card-btn">Read More</button>\n    </div>\n  </div>\n</div>',
    css: 'body { background: #e2e8f0; display: flex; justify-content: center; align-items: center; height: 100vh; font-family: "Segoe UI", sans-serif; margin: 0; }\n.modern-card { background: #fff; border-radius: 20px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.1); width: 320px; transition: transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275); cursor: pointer; }\n.modern-card:hover { transform: translateY(-15px); box-shadow: 0 20px 40px rgba(0,0,0,0.2); }\n.card-img { height: 200px; background: linear-gradient(45deg, #ff9a9e 0%, #fecfef 99%, #fecfef 100%); position: relative; }\n.card-info { padding: 25px; text-align: center; }\n.card-info h3 { margin: 0 0 10px 0; color: #2d3748; font-size: 1.2rem; }\n.card-info p { color: #718096; font-size: 0.9rem; line-height: 1.5; margin-bottom: 20px; }\n.card-btn { background: #ff758c; color: white; border: none; padding: 10px 25px; border-radius: 30px; font-weight: bold; cursor: pointer; transition: background 0.3s, transform 0.2s; }\n.card-btn:hover { background: #ff5e78; transform: scale(1.05); }',
    js: "console.log('Card Component Initialized');"
  },
  'CSS Buttons': {
    html: '<div class="btn-container">\n  <h2>${title}</h2>\n  <div class="buttons">\n    <button class="btn btn-glow">Glow Button</button>\n    <button class="btn btn-swipe">Swipe Hover</button>\n    <button class="btn btn-neumorphic">Neumorphic</button>\n  </div>\n</div>',
    css: 'body { background: #1f2029; display: flex; justify-content: center; align-items: center; height: 100vh; font-family: "Inter", sans-serif; margin: 0; color: #fff; text-align: center;}\nh2 { margin-bottom: 3rem; color: #818cf8; }\n.buttons { display: flex; gap: 2rem; flex-wrap: wrap; justify-content: center; }\n.btn { border: none; padding: 15px 30px; font-size: 1.1rem; font-weight: 600; cursor: pointer; border-radius: 12px; transition: all 0.3s ease; position: relative; overflow: hidden; }\n.btn-glow { background: transparent; color: #00e5ff; border: 2px solid #00e5ff; text-transform: uppercase; box-shadow: 0 0 10px transparent; }\n.btn-glow:hover { box-shadow: 0 0 20px #00e5ff, inset 0 0 20px #00e5ff; background: rgba(0, 229, 255, 0.1); }\n.btn-swipe { background: #818cf8; color: #fff; z-index: 1; }\n.btn-swipe::before { content: ""; position: absolute; top: 0; left: -100%; width: 100%; height: 100%; background: #4f46e5; transition: left 0.4s ease; z-index: -1; }\n.btn-swipe:hover::before { left: 0; }\n.btn-neumorphic { background: #1f2029; color: #a5b4fc; box-shadow: 8px 8px 16px #15161c, -8px -8px 16px #292a36; }\n.btn-neumorphic:hover { box-shadow: inset 6px 6px 12px #15161c, inset -6px -6px 12px #292a36; color: #c7d2fe; }',
    js: "console.log('Buttons ready for action!');"
  },
  'Login Form': {
    html: '<div class="login-container">\n  <form class="glass-form">\n    <h2>${title}</h2>\n    <div class="input-box">\n      <input type="text" required>\n      <label>Username</label>\n    </div>\n    <div class="input-box">\n      <input type="password" required>\n      <label>Password</label>\n    </div>\n    <button type="submit" class="login-btn">Login</button>\n  </form>\n</div>',
    css: 'body { background: url("https://source.unsplash.com/random/1920x1080/?abstract,dark") no-repeat center center/cover; margin: 0; height: 100vh; display: flex; justify-content: center; align-items: center; font-family: "Poppins", sans-serif; }\n.login-container { width: 400px; }\n.glass-form { background: rgba(255, 255, 255, 0.1); backdrop-filter: blur(15px); border: 1px solid rgba(255,255,255,0.2); padding: 40px; border-radius: 20px; box-shadow: 0 25px 45px rgba(0,0,0,0.2); }\nh2 { color: #fff; text-align: center; margin-bottom: 30px; font-size: 24px; }\n.input-box { position: relative; margin-bottom: 30px; }\n.input-box input { width: 100%; padding: 10px 0; font-size: 16px; color: #fff; border: none; border-bottom: 2px solid #fff; outline: none; background: transparent; }\n.input-box label { position: absolute; top: 0; left: 0; padding: 10px 0; font-size: 16px; color: rgba(255,255,255,0.7); pointer-events: none; transition: .5s; }\n.input-box input:focus ~ label, .input-box input:valid ~ label { top: -20px; color: #00e5ff; font-size: 12px; }\n.login-btn { width: 100%; background: #fff; color: #333; border: none; padding: 12px; border-radius: 30px; font-size: 16px; font-weight: bold; cursor: pointer; transition: 0.3s; }\n.login-btn:hover { background: #00e5ff; color: #fff; }',
    js: "document.querySelector('.glass-form').addEventListener('submit', (e) => {\n  e.preventDefault();\n  alert('Login attempted!');\n});"
  },
  'JavaScript': {
    html: '<div class="js-container">\n  <h1>${title}</h1>\n  <div class="interactive-box" id="i-box">Hover or Click Me!</div>\n  <p class="status">Status: Waiting...</p>\n</div>',
    css: 'body { background: #0f172a; color: #f8fafc; font-family: monospace; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; text-align: center; }\n.js-container { max-width: 600px; padding: 2rem; background: #1e293b; border-radius: 1rem; border: 1px solid #334155; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }\nh1 { font-size: 1.5rem; color: #38bdf8; margin-top: 0; }\n.interactive-box { width: 200px; height: 200px; background: #475569; margin: 2rem auto; display: flex; justify-content: center; align-items: center; border-radius: 1rem; cursor: pointer; transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1); font-weight: bold; }\n.interactive-box.active { background: #10b981; transform: scale(1.1) rotate(10deg); box-shadow: 0 0 30px rgba(16, 185, 129, 0.5); }\n.status { color: #94a3b8; font-size: 1.1rem; }',
    js: "const box = document.getElementById('i-box');\nconst status = document.querySelector('.status');\n\nbox.addEventListener('mouseenter', () => { status.textContent = 'Status: Hovering...'; });\nbox.addEventListener('mouseleave', () => { status.textContent = 'Status: Waiting...'; box.classList.remove('active'); });\nbox.addEventListener('click', () => { \n  box.classList.add('active');\n  status.textContent = 'Status: Clicked! Animation triggered.';\n});"
  }
};

const defaultTemplate = templates['HTML & CSS'];
const files = fs.readdirSync(blogDir).filter(f => f.endsWith('.mdx'));
let count = 0;

files.forEach(file => {
  let content = fs.readFileSync(path.join(blogDir, file), 'utf8');
  
  if (content.includes('<!-- Add your HTML content here -->') || content.includes('Add your HTML content here')) {
    const catMatch = content.match(/category:\\s*"(.*?)"/);
    const category = catMatch ? catMatch[1] : 'HTML & CSS';
    const titleMatch = content.match(/seoTitle:\\s*"(.*?)"/);
    const seoTitle = titleMatch ? titleMatch[1] : file.replace('.mdx', '');
    
    const tpl = templates[category] || defaultTemplate;
    
    const replacedHtml = tpl.html.replace(/\\$\\{title\\}/g, seoTitle);
    
    content = content.replace(/\\`\\`\\`html\\n([\\s\\S]*?)\\n\\`\\`\\`/, '```html\\n' + replacedHtml + '\\n```');
    content = content.replace(/\\`\\`\\`css\\n([\\s\\S]*?)\\n\\`\\`\\`/, '```css\\n' + tpl.css + '\\n```');
    content = content.replace(/\\`\\`\\`javascript\\n([\\s\\S]*?)\\n\\`\\`\\`/, '```javascript\\n' + tpl.js + '\\n```');
    
    content = content.replace('<!-- Add your HTML content here -->', '');
    fs.writeFileSync(path.join(blogDir, file), content);
    
    const slug = file.replace('.mdx', '');
    const demoPath = path.join(demosDir, slug + '.html');
    
    const demoHtmlContent = '<!DOCTYPE html>\\n<html lang="en">\\n<head>\\n  <meta charset="UTF-8">\\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\\n  <title>' + seoTitle + ' - Live Demo</title>\\n  <style>\\n' + tpl.css + '\\n  </style>\\n</head>\\n<body>\\n' + replacedHtml + '\\n  <script>\\n' + tpl.js + '\\n  </script>\\n</body>\\n</html>';

    fs.writeFileSync(demoPath, demoHtmlContent);
    console.log('Fixed broken demo: ' + slug);
    count++;
  }
});

console.log('Successfully fixed ' + count + ' broken placeholder components!');
